---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(plotly)
library(p8105.datasets)

data("instacart")

# Data cleaning
instacart |> 
  janitor::clean_names()

avg_orders_per_day <- instacart |> 
  group_by(order_dow) |> 
  summarize(avg_orders = n() / n_distinct(order_id))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Bar Plot of Number of Items Ordered in Each Aisle

```{r}
instacart |> 
  count(aisle) |> 
  filter(n > 10000) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> 
  ggplot(aes(x = aisle, y = n)) + 
  geom_bar(stat = "identity", fill = "blue") + 
  labs(title = "Number of Items Ordered in Each Aisle") + 
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Line Graph of Average Number of Orders per Day of the Week

```{r}
avg_orders_per_day |> 
  ggplot(aes(x = order_dow, y = avg_orders)) + 
  geom_line() + 
  geom_point() + 
  labs(title = "Average Number of Orders per Day of the Week", 
       x = "Day of the Week", 
       y = "Average Number of Orders")
```

### Box and Whisker Plots of Order Hours per Day of the Week

```{r}
instacart |> 
  ggplot(aes(x = factor(order_dow), y = order_hour_of_day)) + 
  geom_boxplot() + 
  labs(title = "Box and Whisker Plot of Order Hours per Day of the Week", 
       x = "Day of the Week", 
       y = "Order Hour of Day")
```
