---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

## This page has information on my academic and professional experience

# Education
Master of Public Health, In Progress – planned graduation 2024
Department of Epidemiology, Certificate in Applied Biostatistics and Public Health Data
GPA: 3.989
Mailman School of Public Health, Columbia University, New York, NY

B.A. in Anthropology, Minor in Public Health, and Minor in Chemistry
George Washington University, Washington, D.C. 2019-2022, Graduated Cum Laude

American University of Paris, Paris, France
2018-2019, Provost’s List

St. Stephen’s and St. Agnes School, Alexandria, VA
2005-2018, Graduated Cum Laude

# Research Experience
Research Assistant
Fetal Heart Society, Children’s National Medical Center, Washington, D.C.
June 2019- March 2020

Student Researcher
Vaccine Unit, Research Center for the Neglected Diseases of Poverty
George Washington University Medical School, Washington, D.C.
October 2019- March 2020

Research Assistant
Cardiac Neurodevelopmental Outcome Program, Children’s National Medical Center, Washington, D.C.
September 2020-May 2022

Research Fellowship
Computational and Statistical Genomics Branch, National Human Genome Research Institute, NIH, Bethesda, Maryland
June 2023-August 2023

# Professional Experience
Internship
Global Services Department, Children’s National Medical Center, Washington, D.C
Summer 2019


Project Intern
Child Health Advocacy Institute, Children’s National Medical Center, Washington, D.C.
Summer 2019

SAT Mathematics Private Tutor, Self-employed
2019-2021

# Publications
Klein J, et al., Demographic patterns of neurodevelopment assessment and care in congenital heart disease, In Progress.

Scheel A, Ssinabulya I, Aliku T, et al. Community study to uncover the full spectrum of rheumatic heart disease in Uganda Heart 2019;105:60-66.

Moore, T., Sewell, J. and Mead, J. 63CW1.15 WSSP Duckweed cDNA library Landoltia punctata cDNA similar to myo-inositol-1-phosphate synthase, mRNA sequence


# University and Community Service
CIPHER, Citizen’s Public Health Literacy
Columbia University’s Mailman School of Public Health
Executive Board, Community Outreach Lead 2022-2023

GW Dance Marathon
Participant, 2019
Team Captain/Participant, 2020
Director of Student Orgs, Executive Board, 2021-2022

Delta Iota Gamma (Anthropology Fraternity, GWU)
Philanthropy Chair 2021-2022

# Extracurriculars
Kappa Alpha Theta, initiated sophomore year
George Washington University

Delta Iota Gamma, initiated junior year.
Anthropology and Classics Pre-Professional Fraternity
George Washington University

GW American Medical Women’s Association
George Washington University

# Languages
English (Native),
French (Conversational/Fluent)

# Coding Languages
SAS,
R,
SQL
